-- Tabla HORA
CREATE TABLE HORA(
    HORA_ID varchar(4) PRIMARY KEY NOT NULL,
    HORA_INICIO time NULL,
    HORA_FIN time NULL
);

-- Tabla SISTEMA
CREATE TABLE SISTEMA(
    SISTEMA_ID varchar(4) PRIMARY KEY NOT NULL,
    SISTEMA_NOMBRE varchar(10) NULL
);

-- Tabla DRON
CREATE TABLE DRON (
    DRON_ID varchar(4)  PRIMARY KEY NOT NULL,
    DR_SISTEMA_ID varchar(4) NULL,
    DRON_NOMBRE varchar(30) NULL,

    CONSTRAINT FK_DRON_SISTEMA_D_SISTEMA FOREIGN KEY (DR_SISTEMA_ID)
    REFERENCES SISTEMA (SISTEMA_ID)
    ON DELETE restrict ON UPDATE restrict
);

-- Tabla DRON_HORA
CREATE TABLE DRON_HORA (
    DR_DRON_ID varchar (4) NOT NULL,
    DR_HORA_ID varchar(4)  NOT NULL,

    CONSTRAINT FK_DRON_HOR_DRON_HORA_DRON FOREIGN KEY (DR_DRON_ID)
    REFERENCES DRON (DRON_ID)
    ON DELETE restrict ON UPDATE restrict,

    CONSTRAINT FK_DRON_HOR_DRON_HORA_HORA FOREIGN KEY (DR_HORA_ID)
    REFERENCES HORA (HORA_ID)
    ON DELETE restrict ON UPDATE restrict
);
